<a href="https://colab.research.google.com/github/enhaaa88/coba01/blob/main/svm_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
clf = SVC(kernel='linear')

In [2]:
#importing the dataset
df = pd.read_csv('tryout.csv')
df.head()

Rank          NIS                    Nama        Sekolah  \
0     1  20307332037      Rizqi Zuhdi Amarta  SMAN 1 PADANG   
1     2  20307331061  Resti Natalia Chaniago  SMAN 5 PADANG   
2     3  20307331062        Indah Widia Sari  SMAN 5 PADANG   
3     4  20307332049                 Mulyadi   MAN 2 PADANG   
4     5  20307331058          Elfaiza Warsya   SMA DONBOSCO   

                       PTN                            Jurusan      PG  \
0   UNIVERSITAS GAJAH MADA  BANGUNAN SOSIAL DAN KESEJAHTERAAN  653.11   
1  UNIVERSITAS GADJAH MADA                            SEJARAH  484.58   
2    UNIVERSITAS INDONESIA                     SASTRA INGGRIS  481.70   
3    UNIVERSITAS INDONESIA                   SASTRA INDONESIA  465.99   
4    UNIVERSITAS INDONESIA           ILMU ADMINISTRASI NEGARA  485.77   

   Penalaran Umum  Pemahaman Bacaan & Menulis  Pengetahuan & Pemahaman Umum  \
0          709.99                      475.55                        597.82   
1          560.00                      525.00                        595.00   
2          595.00                      525.00                        560.00   
3          560.00                      525.00                        560.00   
4          595.00                      560.00                        490.00   

   Pengetahuan Kuantitatif  Bahasa Inggris  Ekonomi  Geografi  Sosiologi  \
0                   658.11          672.36   620.79    622.09     558.76   
1                   595.00          574.00   560.00    560.00     560.00   
2                   560.00          560.00   560.00    525.00     595.00   
3                   525.00          542.50   560.00    525.00     560.00   
4                   560.00          546.00   525.00    595.00     490.00   

   Sejarah  Nilai TPS  Nilai TKA  Skor UTBK       Status  
0   641.77     622.76     610.85    617.470  BELUM LULUS  
1   595.00     568.75     569.80    569.275        LULUS  
2   560.00     560.00     560.00    560.000        LULUS  
3   525.00     542.50     542.50    542.500        LULUS  
4   490.00     551.25     529.20    540.225        LULUS

In [3]:
x = df.iloc[:,[16,17]].values
y = df.iloc[:, -1].values
print(x[0:5])

[[622.76 610.85]
 [568.75 569.8 ]
 [560.   560.  ]
 [542.5  542.5 ]
 [551.25 529.2 ]]


In [4]:
print(y[0:5])

['BELUM LULUS' 'LULUS' 'LULUS' 'LULUS' 'LULUS']


In [5]:
#Splitting the dataset into the Training set and Test set
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.29, random_state =0)

In [6]:
#scalling feature
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform (x_test)

In [7]:
print(x_train[0:5])

[[-0.84094787  0.38449887]
 [ 0.8600694   0.98839496]
 [-0.56878511  0.69935068]
 [ 0.51986595  0.76128874]
 [ 0.72398802  0.85935734]]


In [8]:
print(x_test[0:5])

[[ 0.29575935  0.38368778]
 [ 0.45182525  0.23997673]
 [-0.70486649  0.39482188]
 [ 0.17966249  0.60644359]
 [ 0.31574387  0.27610727]]


In [9]:
#Training the Kernel SVM model on the Training set
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [10]:
#Predicting the Test set results
y_predict = classifier.predict(x_test)

In [15]:
y_predict[0:5]

array(['LULUS', 'LULUS', 'BELUM LULUS', 'LULUS', 'BELUM LULUS'],
      dtype=object)

In [14]:
#making the confusion matrix

clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print('Accuracy:')
print((y_test==y_pred).sum()/len(y_pred))

Accuracy:
0.9047619047619048
